service: JobCreator 

provider:
  name: aws
  runtime: python3.7
  profile: aws-personal
  region: eu-west-1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  job_creator:
    handler: handler.job_creator
    events:
      - schedule: rate(2 minutes)
