service: JobCreator 

provider:
  name: aws
  runtime: python3.7
  profile: aws-personal
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
        - "cloudformation:ListStacks"
        - "cloudformation:CreateStack"
        - "cloudformation:UpdateStack"
        - "cloudformation:DeleteStack"
      Resource: '*'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  job_creator:
    handler: handler.job_creator
    timeout: 60
    events:
      - schedule: rate(2 minutes)
